# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_medico_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='Doc',
            field=models.IntegerField(),
        ),
    ]
