# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('edad', models.IntegerField()),
                ('Doc', models.IntegerField()),
                ('domicilio', models.CharField(max_length=10)),
                ('colegio', models.CharField(max_length=10)),
                ('grado', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('madre', models.CharField(max_length=10)),
                ('padre', models.CharField(max_length=10)),
                ('telefono', models.IntegerField()),
                ('observacion_Entorno_familiar', models.CharField(max_length=4000)),
                ('motivo_consulta', models.CharField(max_length=1000)),
                ('antecedentes_personales', models.CharField(max_length=1000)),
                ('alergicos', models.CharField(max_length=100)),
                ('examen_fisico', models.CharField(max_length=100)),
                ('fc', models.IntegerField()),
                ('fr', models.IntegerField()),
                ('pc', models.IntegerField()),
                ('talla', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('pa', models.IntegerField()),
                ('imc', models.IntegerField()),
                ('av', models.IntegerField()),
                ('cabeza_cuello', models.CharField(max_length=100)),
                ('cardio_pulmonar', models.CharField(max_length=100)),
                ('abdomen', models.CharField(max_length=100)),
                ('extremidades', models.CharField(max_length=100)),
                ('piel_anexos', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=400)),
                ('Medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.Medico')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='vacuna',
            field=models.ManyToManyField(blank=True, to='pacientes.Vacuna'),
        ),
    ]
