# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20160905_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='antecedentes_personales',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='motivo_consulta',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
    ]
