# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_auto_20160912_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='talla',
            field=models.IntegerField(),
        ),
    ]
