# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_auto_20160912_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='talla',
            field=models.FloatField(),
        ),
    ]
