# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('formula', '0001_initial'),
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulas',
            name='medicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.Medico'),
        ),
        migrations.AddField(
            model_name='formulas',
            name='pacientes_f',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente'),
        ),
    ]
