# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-24 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0002_auto_20161011_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulas',
            name='hora',
            field=models.TimeField(default='06:30 PM'),
            preserve_default=False,
        ),
    ]
