# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-27 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0003_formulas_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulas',
            name='formula',
        ),
        migrations.AddField(
            model_name='formulas',
            name='cantidad',
            field=models.CharField(default='06:30', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulas',
            name='cantidad_dos',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='formulas',
            name='cantidad_tres',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='formulas',
            name='dosificacion',
            field=models.CharField(default='05:30', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulas',
            name='dosificacion_dos',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='formulas',
            name='dosificacion_tres',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='formulas',
            name='medicamento',
            field=models.CharField(default='13:45:2', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulas',
            name='medicamento_dos',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='formulas',
            name='medicamento_tres',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='formulas',
            name='observaciones',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
