# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-27 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0004_auto_20161027_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulas',
            old_name='cantidad_dos',
            new_name='cantidad2',
        ),
        migrations.RenameField(
            model_name='formulas',
            old_name='cantidad_tres',
            new_name='cantidad3',
        ),
        migrations.RenameField(
            model_name='formulas',
            old_name='dosificacion_dos',
            new_name='dosificacion2',
        ),
        migrations.RenameField(
            model_name='formulas',
            old_name='dosificacion_tres',
            new_name='dosificacion3',
        ),
        migrations.RenameField(
            model_name='formulas',
            old_name='medicamento_dos',
            new_name='medicamento2',
        ),
        migrations.RenameField(
            model_name='formulas',
            old_name='medicamento_tres',
            new_name='medicamento3',
        ),
    ]
