# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-27 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0005_auto_20161027_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulas',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='cantidad2',
            field=models.IntegerField(default='3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulas',
            name='cantidad3',
            field=models.IntegerField(default='5'),
            preserve_default=False,
        ),
    ]
