# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0006_auto_20161027_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulas',
            name='cantidad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='cantidad2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='cantidad3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
