# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='vacuna',
            field=models.ImageField(upload_to='vacuna'),
        ),
    ]
