# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='pacientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente'),
        ),
    ]
